apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-cert
  namespace: networking
spec:
  # Secret names are always required.
  secretName: unifi-tls
  dnsNames:
    - "unifi.home.andrewmccall.com"
  ipAddresses:
    - 10.44.0.3
  issuerRef:
    name: letsencrypt-production