apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-cert
  namespace: networking
spec:
  # Secret names are always required.
  secretName: unifi-tls
  dnsNames:
    - "unifi.${DOMAIN}"
  ipAddresses:
    - ${UNIFI_IP}