apiVersion: v1
kind: ConfigMap
metadata:
    name: unifi-config-gateway
    namespace: networking
data:
    config.gateway.json: |
        {  
            "protocols": {
                "bgp": {
                    "64512": {
                        "neighbor": {
                            "10.0.0.250": {
                                "remote-as": "64513"
                            }
                        },
                        "parameters": {
                            "router-id": "10.0.0.1"
                        }
                    }
                }
        }
