---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: unifi
      # renovate: datasource=helm registryUrl=https://home-ops.andrewmccall.com/charts/stable chart=unifi
      version: 1.0.4
      sourceRef:
        kind: HelmRepository
        name: home-ops
        namespace: flux-system
  values:
    replicas: 1
    isClusterService: false
    service:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "unifi.${DOMAIN}"
        type: LoadBalancer
        externalIPs:
          - ${UNIFI_IP}
        externalTrafficPolicy: Local
    persistence:
      data:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 1Gi
        mountPath: /unifi
      certs:
        enabled: true
        name: unifi-tls
        type: secret
        mountPath: /unifi/cert
      gatewayconfig:
        enabled: true
        name: unifi-config-gateway
        type: configMap
        mountPath: /unifi/data/sites/default/config.gateway.json
        subPath: config.gateway.json
    env:
      CERTNAME: tls.crt
      CERT_PRIVATE_NAME: tls.key
      CERT_IS_CHAIN: true
