---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  chart:
    spec:
      chart: unifi
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m0s
  values:
    replicaCount: 1
    isClusterService: false
    serviceType: LoadBalancer
    service:
      externalIPs:
        - ${UNIFI_IP}
      externalTrafficPolicy: Local

