---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: unifi
      # renovate: datasource=helm registryUrl=https://home-ops.andrewmccall.com/charts/stable chart=unifi
      version: 1.0.4
      sourceRef:
        kind: HelmRepository
        name: home-ops
        namespace: flux-system
  values:
    replicas: 1
    isClusterService: false
    service:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "unifi.${DOMAIN}"
        type: LoadBalancer
        externalIPs:
          - ${UNIFI_IP}
        externalTrafficPolicy: Local
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 1Gi
    

