---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: unifi
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: home-ops
        namespace: flux-system
  values:
    replicas: 1
    isClusterService: false
    service:
      main:
        type: LoadBalancer
        externalIPs:
          - ${UNIFI_IP}2
        externalTrafficPolicy: Local
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 1Gi
