---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  chart:
    spec:
      chart: unifi
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      values: 
        service:
          externalIPs:
            - 10.0.0.5
          externalTrafficPolicy: Local
  interval: 5m0s

