---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: unifi
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values: 
    replicaCount: 1
    isClusterService: false
    serviceType: LoadBalancer
    service:
      main:
        externalIPs:
          - ${UNIFI_IP}
        externalTrafficPolicy: Local
