---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      # renovate: datasource=helm registryUrl=https://grafana.github.io/helm-charts chart=grafana
      version: 8.5.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    env:
      VAR_BLOCKY_URL: "http://blocky.networking.svc.${CLUSTER_DOMAIN}:4000"
    adminPassword: ${GRAFANA_ADMIN_PASSWORD}
    grafana.ini:
      analytics:
        check_for_updates: false
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL
    plugins:
      - grafana-clock-panel
      - grafana-piechart-panel
      - grafana-worldmap-panel
      - natel-discrete-panel
      - pr0ps-trackmap-panel
      - vonage-status-panel
    serviceMonitor:
      enabled: true
    ingress:
      enabled: true
      hosts: ["grafana.${DOMAIN}"]
    persistence:
      enabled: true
      existingClaim: grafana-config
