---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      # renovate: datasource=helm registryUrl=https://grafana.github.io/helm-charts chart=grafana
      version: 8.4.5
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    env:
      VAR_BLOCKY_URL: "http://blocky.networking.svc.${CLUSTER_DOMAIN}:4000"
    adminPassword: ${GRAFANA_ADMIN_PASSWORD}
    grafana.ini:
      analytics:
        check_for_updates: false
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL
    plugins:
      - natel-discrete-panel
      - pr0ps-trackmap-panel
      - grafana-piechart-panel
      - vonage-status-panel
      - grafana-worldmap-panel
      - grafana-clock-panel
    serviceMonitor:
      enabled: true
    ingress:
      enabled: true
      annotations:
        external-dns.home.arpa/enabled: "true"
        cert-manager.home.arpa/enabled: "true"
        auth.home.arpa/enabled: "true"
      tls:
        - hosts:
            - grafana.${DOMAIN}
          secretName: grafana-tls
    persistence:
      enabled: true
      existingClaim: grafana-config
