#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/andrewmccall/home-ops/tree/main/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: itzg/minecraft-bedrock-server
  # @default -- chart.appVersion
  tag:
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        enabled: false
      server:
        enabled: true
        port: 19132
        protocol: UDP

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: /data
