---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: house
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      # renovate: datasource=helm registryUrl=https://bjw-s-labs.github.io/helm-charts chart=app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              # renovate: datasource=docker tag=home-assistant/home-assistant
              tag: 2026.1.3@sha256:c36741490472518338323db8ee67775d7df70d2fa1f68eff9b9e63679fe64a18
            env:
              TZ: Europe/London
              HASS_HTTP_TRUSTED_PROXY_1: ${K8S_CLUSTER_CIDR}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.108.2@sha256:31ad23cda720476e7eb3371a9b02fd7a5738843f6ef43beef97e9edf1960fc47
            args: [
              "--auth", "none",
              "--user-data-dir", "/config/.vscode",
              "--extensions-dir", "/config/.vscode",
              "--port", "12321",
              "/config"
            ]
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
      voice:
        containers:
          whisper:
            image:
              repository: rhasspy/wyoming-whisper
              # renovate: datasource=docker rhasspy/wyoming-whisper
              tag: 3.1.0@sha256:9501d2659eee83b6eead98d53842193e5fed011eda6c5b1c3ad36f3146b28fed
          piper:
            image:
              repository: rhasspy/wyoming-piper
              # renovate: datasource=docker rhasspy/wyoming-piper
              tag: 2.1.2
            args: ["--voice", "en_GB-alan-medium"]
    service:
      app:
        controller: home-assistant
        ports:
          http:
            port: 8123
          code-server:
            port: 12321
      voice: 
        controller: voice
        ports: 
          whisper-wyoming:
            port: 10300
          piper-wyoming:
            port: 10200
    ingress:
      app:
        className: external
        hosts:
          - host: home-assistant.${DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
      code-server:
        className: internal
        hosts:
          - host: home-assistant-code.${DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: code-server
    persistence:
      config:
        existingClaim: home-assistant-config
        globalMounts:
          - path: /config
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      tts:
        type: emptyDir
        globalMounts:
          - path: /config/tts
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      whisper-data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 50Gi
        advancedMounts:
          voice:
            whisper-wyoming:
              - path: /data
      piper-data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 50Gi
        advancedMounts:
          voice:
            piper-wyoming:
              - path: /data
