---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: house
spec:
  interval: 10m
  chart:
    spec:
      chart: home-assistant
      # renovate: datasource=helm registryUrl=https://home-ops.andrewmccall.com/charts/stable chart=home-assistant
      version: 2024.8.302
      sourceRef:
        kind: HelmRepository
        name: home-ops
        namespace: flux-system
  values:
    replicas: 1
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config 
    ingress:
      main:
        enabled: true
        annotations:
          nginx.org/websocket-services: home-assistant
        hosts:
          - host: home-assistant.${DOMAIN}
            paths:
              - path: /
      