---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      # renovate: datasource=helm registryUrl=https://grafana.github.io/helm-charts chart=loki
      version: 6.55.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    global:
      clusterDomain: ${CLUSTER_DOMAIN}
    deploymentMode: SingleBinary
    singleBinary:
      replicas: 1
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    loki:
      auth_enabled: false
      useTestSchema: true
      storage:
        type: "filesystem"
      commonConfig:
        replication_factor: 1
      limits_config:
        retention_period: 720h  # 30 days
        max_query_series: 500
      compactor:
        working_directory: /var/loki/compactor
        compaction_interval: 10m
        retention_enabled: true
        retention_delete_delay: 2h
        retention_delete_worker_count: 150
        delete_request_store: filesystem
    gateway:
      ingress:
        enabled: true
        ingressClassName: internal
        annotations:
          cert-manager.home.arpa/enabled: "true"
        hosts:
          - host: &host "loki.${DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: loki-tls
    monitoring:
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
  # values generated by the creation of the ObjectBucketClaim
  #valuesFrom:
  #  - targetPath: loki.storage.bucketNames.chunks
  #    kind: ConfigMap
  #    name: loki-chunks-bucket
  #    valuesKey: BUCKET_NAME
  #  - targetPath: loki.storage.bucketNames.ruler
  #    kind: ConfigMap
  #    name: loki-chunks-bucket
  #    valuesKey: BUCKET_NAME
  #  - targetPath: loki.storage.bucketNames.admin
  #   kind: ConfigMap
  #    name: loki-chunks-bucket
  #    valuesKey: BUCKET_NAME
  #  - targetPath: loki.storage.s3.endpoint
  #    kind: ConfigMap
  #    name: loki-chunks-bucket
  #    valuesKey: BUCKET_HOST
  #  - targetPath: loki.storage.s3.accessKeyId
  #    kind: Secret
  #    name: loki-chunks-bucket
  #    valuesKey: AWS_ACCESS_KEY_ID
  #  - targetPath: loki.storage.s3.secretAccessKey
  #    kind: Secret
  #    name: loki-chunks-bucket
  #    valuesKey: AWS_SECRET_ACCESS_KEY
