---
ansible_become: yes
packages:
  install:
    - linux-modules-extra-raspi
    - apt-transport-https
    - arptables
    - ebtables
    - nfs-common
    - open-iscsi
  remove:
    - apparmor
    - snapd
