---
creation_rules:
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: '^(data|stringData)$'
    age: >-
      age16rj2w4scur86mjvs6eutq03cwlpygu3pywcedvl0rkh68vzv0dlqagqenq
  - filename_regex: os/vars\.enc\.yaml$
    age: age16rj2w4scur86mjvs6eutq03cwlpygu3pywcedvl0rkh68vzv0dlqagqenq