---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openclaw-operator
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/apps/openclaw/operator
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: openclaw-operator
      namespace: openclaw-operator-system
