---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: esp-home
  namespace: house
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      # renovate: datasource=helm registryUrl=https://bjw-s-labs.github.io/helm-charts chart=app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      esphome:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/esphome/esphome
              tag: 2026.1.1@sha256:4935613e12d91028ff7e4d711906879d5e4e36f927f5db6509442fc45909cdd0
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/London
              # From https://github.com/ptr727/ESPHome-NonRoot
              PLATFORMIO_CORE_DIR: /cache/pio
              # ESPHome "build_path" option, default is "/config/.esphome/build/[project]"
              ESPHOME_BUILD_PATH: /cache/build
              # ESPHome "data_dir" option, default is "/config/.esphome"
              ESPHOME_DATA_DIR: /cache/data
              # Set pip cache directory, default is "~/.cache/pip"
              PIP_CACHE_DIR: /cache/pip
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
          code:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.108.2@sha256:31ad23cda720476e7eb3371a9b02fd7a5738843f6ef43beef97e9edf1960fc47
              pullPolicy: IfNotPresent
            args:
              - --disable-telemetry
              - --disable-update-check
              - --auth=none
              - --user-data-dir=/cache
              - --extensions-dir=/cache
              - /config
            resources:
              requests:
                cpu: 0m
                memory: 50Mi
              limits:
                cpu: 500m
                memory: 500Mi
    service:
      esphome:
        controller: esphome
        ports:
          http:
            port: 6052
          code:
            port: 8080
    ingress:
      esphome:
        className: internal
        hosts:
          - host: esphome.${DOMAIN}
            paths:
              - path: /
                service:
                  identifier: esphome
                  port: http
      code-server:
        className: internal
        hosts:
          - host: esphome-code.${DOMAIN}
            paths:
              - path: /
                service:
                  identifier: esphome
                  port: code
    persistence:
      config:
        existingClaim: esp-home-config
        globalMounts:
          - path: /config
      cache:
        existingClaim: esp-home-cache
        globalMounts:
          - path: /cache
      
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp