---

- name: Install a .deb package from the internet
  ansible.builtin.apt:
    deb: "{{ camera_streamer_repo }}/camera-streamer-raspi_{{ camera_streamer_version }}.bookworm_arm64.deb"

- name: Copy startup file
  ansible.builtin.copy:
    src: /srv/myfiles/foo.conf
    dest: /etc/foo.conf
    owner: foo
    group: foo
    mode: '0644'
