---

- name: Install a .deb package from the internet
  ansible.builtin.apt:
    deb: "{{ camera_streamer_repo }}/camera-streamer-raspi_{{ camera_streamer_version }}.bookworm_arm64.deb"

- name: Copy systemd file
  ansible.builtin.copy:
    src: "{{ inventory_hostname }}/picamera/camera-streamer.service"
    dest: /etc/systemd/system/camera-streamer.service
    mode: "644"

- name: Enable systemd unit
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: camera-streamer.service
  notify: Restart Camera Service