---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquito
  namespace: databases
spec:
  interval: 10m
  chart:
    spec:
      chart: mosquito
      # renovate: datasource=helm registryUrl=https://home-ops.andrewmccall.com/charts/stable chart=mosquito
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: home-ops
        namespace: flux-system
  values:
    persistence:
      data:
        enabled: true
      configinc:
        enabled: true
