---
- import_tasks: time.yml
  tags:
    - time

- import_tasks: packages.yml
  tags:
    - packages

- import_tasks: kernel.yml
  tags:
    - kernel

- import_tasks: network.yml
  tags:
    - network

- import_tasks: filesystem.yml
  tags:
    - filesystem

- import_tasks: journald.yml
  tags:
    - journald

- import_tasks: unattended-upgrades.yml
  tags:
    - unattended-upgrades
