---
k3s_control_node: yes

k3s_server:
  cluster-cidr: 10.42.0.0/16
  service-cidr: 10.43.0.0/16
  cluster-domain: cluster.milkyway
  tls-san:
    - "betelguese"
  node-label:
    - "k3s-upgrade=true"
