#ENC[AES256_GCM,data:TvP/oZ7taQxFUVlRBxcYV3A=,iv:dN2riwvjLqRUSjLmm8oCJp/x8W4uE2yMKHApm7BQdb0=,tag:sRgeU0eUBC6kd3U8cpd7cg==,type:comment]
apiVersion: ENC[AES256_GCM,data:bxU=,iv:JYfKSknyWeAQEnW2IOny7vhAkDK6xCbDfgZiG0NorGA=,tag:HujPIMvIrDi95Roei1ysww==,type:str]
kind: ENC[AES256_GCM,data:IA/l1YWl,iv:DfCy2HVHEn7N8XG7mi9dD+Wk02boAivRDVk1bYO6KPE=,tag:BtsBTsyeD0b/0af07PQSAg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gilvzYc6b406pQDrs1mO8tw=,iv:b2FOQvVHDwksSSC//7TgzTBwjNJe3fK2S/Uy2f16QH8=,tag:nTGD0RrsviU0lPMzDR5zng==,type:str]
    namespace: ENC[AES256_GCM,data:dZPoo+ne0zvZGw==,iv:9qzHXvbvXYeocYbsvbflVhSdXBJBs4bYm+k19gMekpE=,tag:zrkPYhDr6tX4e/71j9MIGw==,type:str]
data:
    UNIFI_HOST: ENC[AES256_GCM,data:eOD6kR4mbrY=,iv:GRqi7d6G8lVMH7fMeH1NYKlqD4rWOXNCfnDqNThajcA=,tag:RzBRKdenkVeGemPVZTFlfA==,type:str]
    UNIFI_USER: ENC[AES256_GCM,data:PnaP7OYMSJEpJm0s,iv:n6rOYllCSWdkYcGm4KjOAaHotqCazJp6/1tGhzy8SMg=,tag:cxIg8b7AQuVY3FT+f/HBJQ==,type:str]
    UNIFI_PASS: ENC[AES256_GCM,data:crzhUgKjRoIsn8xkIuCfFA==,iv:rT1uveJB/IoUjL6rG7osDlxH0g0fuYGyfN8Ad5ds9BQ=,tag:t9haOSyXYei9bNjpz6EIlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rj2w4scur86mjvs6eutq03cwlpygu3pywcedvl0rkh68vzv0dlqagqenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZSttOUllQnlUUDRza1li
            YUF6aDcvc3NIMERLYkx5TkdwdFR3d3FGMmhFCmFYdUY2QTUycE5ERHN3QTJzL1BT
            eFNpaStCdUQya0laamV6UnlRNC9hVmcKLS0tIG9jRVQxWlhTa0RMOHJtY3c1MkZz
            OUpOZk5raVRsWkRWUTdqYWdHRERZZ1kKgtQJrkQwSyo4lRKA8f5aX3SWdGZMRnIS
            xLPkWagJA7mKWb3LIhjruo4Dd1lGmfxekWcT9hW5Vyzj6MhFfBk/pQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-22T15:24:57Z"
    mac: ENC[AES256_GCM,data:hFPoSYDYpw7VPJnSjg2Tw33YJtlBajl7nKeIorxegFJC49TLGCBy2NIAY4xi7nbfiYb4n/mPspkA5hcQxyhBJJB32F5+Fe3QbkBW7dvnxazjgseZLoIH6+Exs6ypqWIV3iZxVrVui1Ap1/VfULIimJe2y7zucaF12LU4yPFK3xc=,iv:ryMZKwFIhSmg7ILysQpmKAdB2jS0C5C3PxkHnLfKqdQ=,tag:81ziijCyQJvpBlLQP5/lRg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
