apiVersion: v1
kind: Secret
metadata:
    name: external-dns-unifi-secret
    namespace: networking
type: Opaque
stringData:
    UNIFI_HOST: ENC[AES256_GCM,data:eZdL06lcuvzn6SSWTKvj,iv:eRCz0PL5/L/LHFt288zOXWTWc44Gbn3K45G8u+PmAn8=,tag:H/FQxEvviAHIUyZH97TkJA==,type:str]
    UNIFI_API_KEY: ENC[AES256_GCM,data:zoTWkq6Efidl7CyVbSo4yYGAR+HI2Mlk5GWb6SDicAQ=,iv:5+9BCpTCt8Jy5DX+H2lZg+ubhyfRJimrjXOzCaMYIgE=,tag:pwCBHmQbrR6u8AXywrLS8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rj2w4scur86mjvs6eutq03cwlpygu3pywcedvl0rkh68vzv0dlqagqenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsa3pGY1RDb0RZVnVkV29k
            TnB3T3paczZTTmdXZHVCWllyQ0dRcnoranhFCnNkajE2UHVhVVUzR1BuQkIzaUlW
            dTBIcjM5S3hCZlM1eWxxTEcwN3EwM3cKLS0tIERzZW9PdG43Q0pFNStwc1ZQQUxI
            NWU3cUpxR3RyZ09JZkk0RU5VS2ZpaXMKeAbXj1lG+L+Ju1zdjulGVn0u0RtQt1Db
            vtRIjZMxwRx+wuIclWHL3vXrOvJtO6L/FTxFPos6Sf253xj0hJ2ZRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T19:44:54Z"
    mac: ENC[AES256_GCM,data:hesAP1nCTqyqw3qPuH964lKlYRz13NSIkJcUSZmi3fhVEd8iLB0ExTnz9j8pvbsCzD0rIfMAW/GuUORESEND0v9PJ0akC8DC7BCN1OsK6GMSpUup7r8dpUCW6h+RK0B+WYQIDjyuYvUrc3DLFnTIZQIWJbIZ7vfZ0WmIK6aUVic=,iv:hkTT9crKHIBHXYBvmIonfxxER6OKTnT3tdGJTZ8StGM=,tag:JkNlEIJSIrkbRq8cZfMf7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0