# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: unifi-credentials
    namespace: networking
type: Opaque
stringData:
    UNIFI_HOST: ENC[AES256_GCM,data:NdFjHwsJAN4=,iv:fdskn1MeuIVFNnQBHXfcmAtHAlI22EBc7lgShHViNFQ=,tag:X1FdOgzkSipbYPkUgeusYQ==,type:str]
    UNIFI_USER: ENC[AES256_GCM,data:c+uNvye1PhZ6J0gT,iv:/IPkZOh5auf1LQGpGFp5mUww8BDVEHsftqbIhQ5dR6o=,tag:4JD2xkUGQwUbSIi0FbwUFA==,type:str]
    UNIFI_PASS: ENC[AES256_GCM,data:gu8cxwKL+yzNncPR8i2Hlg==,iv:Q1adizf+Axl7XAwnOFGbxr0aSk5h78LSmAad/N21CPc=,tag:xakERapUucHy411b0dOa/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rj2w4scur86mjvs6eutq03cwlpygu3pywcedvl0rkh68vzv0dlqagqenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMc1BEdHpZL2l0UGtRdXRy
            QnZpQWhxaXR1SFdabWttQkFIYWp0OGxMa1hVCjNSZ1lkeE4vWG1odldqR1JtUkpv
            UlZHVThHbkRERnBvM3czOUFzR3hRZWMKLS0tIDcyMm1PaUFyQkUrWGo5TjVKN1dJ
            VGMzOEhQcE5zZ2FNckJHV2NOeEhGZncKsD9ZdW99yNZ7I7Odu1jzYPPYIC+XeXIm
            1t/8u1VQNKlEjariXpQPPcYQeINXG6Fo3y/oHhLz5WujmeKINrlB7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-22T16:47:40Z"
    mac: ENC[AES256_GCM,data:lyLL989TDX+dy3wLRlJCD8L3LhLAzrsp6ohL2Y9JZZFA9JjF5Y+S7mVSYMb4GaW7t7OIl5DOKqyKVb8Vlkejm0L7UNHeA1iuM0BUYJJTyMPrnCKinezjXu/f+YdJPuZGmHqU1Qutt3lJfcUepM5aYjdxplVwmwbcSqPUJd/R2qM=,iv:Fc9i8jdaad+7CFYDmlp5S00ctoWg7KsZAUal/GG4jrY=,tag:RT7Dpdg8/CW5wy/YYis9sA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
