---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-cloudflare
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    sources:
      - ingress
    provider: cloudflare
    cloudflare:
      secretName: cloudflare-api-token
    policy: sync
    domainFilters:
      - ${DOMAIN}
    extraArgs:
      - --cloudflare-proxied
      - --annotation-filter=external-dns.home.arpa/enabled in (true)
    serviceMonitor:
      enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 50m
        memory: 50Mi
