---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-unifi
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: 1.20.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    fullnameOverride: external-dns-unifi
    logLevel: &logLevel debug 
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/kashalls/external-dns-unifi-webhook
          tag: v0.8.2@sha256:7f0ddbbc83a36a2a9d762e25eef9cafcb3adf0493068a27d72ae71087eafe6f0
        env:
          - name: UNIFI_HOST
            valueFrom:
              secretKeyRef:
                name: external-dns-unifi-secret
                key: UNIFI_HOST
          - name: UNIFI_SITE
            value: ""
          - name: UNIFI_EXTERNAL_CONTROLLER
            value: "false"
          - name: UNIFI_API_KEY
            valueFrom:
              secretKeyRef:
                name: external-dns-unifi-secret
                key: UNIFI_API_KEY
          - name: LOG_LEVEL
            value: *logLevel
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
      extraArgs:
        - --ignore-ingress-tls-spec
      policy: sync
      sources: ["ingress", "service"]
      txtOwnerId: default
      txtPrefix: k8s.
      domainFilters: ["${DOMAIN}"] 
