---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: 1.12.1
      sourceRef:
        kind: HelmRepository
        # renovate: datasource=helm registryUrl=https://kubernetes-sigs.github.io/external-dns chart=external-dns
        name: external-dns
        namespace: flux-system
  values:
    provider: coredns
    env:
      - name: ETCD_URLS
        value: http://etcd-extdns:2379
    policy: sync
    domainFilters:
      - ${DOMAIN}
    serviceMonitor:
      enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 50m
        memory: 50Mi
