---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        # renovate: datasource=helm registryUrl=https://kubernetes-sigs.github.io/external-dns chart=external-dns
        name: external-dns
        namespace: flux-system
  values:
    logLevel: debug
    provider: coredns
    env:
      - name: ETCD_URLS
        value: http://${ETCD_EXTDNS_IP}:2379
    policy: sync
    sources: ["ingress", "service"]
    domainFilters: ["${DOMAIN}"]
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 50m
        memory: 50Mi
