---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: 1.14.4
      sourceRef:
        kind: HelmRepository
        # renovate: datasource=helm registryUrl=https://kubernetes-sigs.github.io/external-dns chart=external-dns
        name: external-dns
        namespace: flux-system
  values:
    logLevel: debug
    provider: coredns
    env:
      - name: ETCD_URLS
        value: http://${ETCD_EXTDNS_IP}:2379
    policy: sync
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 50m
        memory: 50Mi
