---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: k8s-gateway
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway
        namespace: flux-system

  values:
    image:
      registry: quay.io
      repository: oriedge/k8s_gateway
      tag: v0.3.2
    replicaCount: 1
    domain: ${DOMAIN}
    service:
      type: LoadBalancer
      externalIPs:
        - ${K8S_GATEWAY_IP}
      externalTrafficPolicy: Local
    extraZonePlugins:
      - name: log
      - name: errors
      - name: health
        configBlock: |-
          lameduck 5s
      - name: ready
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: forward
        parameters: . ${COREDNS_IP}
        configBlock: |-
          tls_servername cloudflare-dns.com
      - name: loop
      - name: reload
      - name: loadbalance
