---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vector-agent
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: vector
      # renovate: datasource=helm registryUrl=https://helm.vector.dev chart=vector
      version: 0.41.0
      sourceRef:
        kind: HelmRepository
        name: vector
        namespace: flux-system
  dependsOn:
    - name: vector-aggregator
      namespace: monitoring
  values:
    image:
      repository: timberio/vector
      tag: 0.45.0-debian@sha256:987a15ebfb2eac3a4d5efb26252d140f799553feffb753dc215bdf738a7d4174
    role: Agent
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: false
      sources:
        journal_logs:
          type: journald
          journal_directory: /var/log/journal
        kubernetes_logs:
          type: kubernetes_logs
        vector_metrics:
          type: internal_metrics
      sinks:
        journal_sink:
          type: vector
          inputs:
            - journal_logs
          address: vector-aggregator:6000
          version: "2"
        kubernetes_sink:
          type: vector
          inputs:
            - kubernetes_logs
          address: vector-aggregator:6010
          version: "2"
        prometheus_sink:
          type: prometheus_exporter
          inputs:
            - vector_metrics
          address: 0.0.0.0:9090
    service:
      enabled: false
    podMonitor:
      enabled: true
      jobLabel: vector-agent
      port: prometheus-sink
    securityContext:
      privileged: true
