---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openclaw
resources:
  - litellm.yaml
  - litellm-secrets.sops.yaml
  - openai-proxy-tls-secret.yaml
  - openai-proxy-ingress.yaml
