apiVersion: v1
kind: Secret
metadata:
    name: litellm-secrets
    namespace: openclaw
stringData:
    gateway-token: ENC[AES256_GCM,data:hb5u+bqnkrqMWCPisIXDFhpXS8IMK6Do26lDl14GRxMVlsKoTVGaEXwwK+6WinpGJTkdmB9FbnLQWm+gpUbDWQ==,iv:+JpKzgZUKImBKTQW0dI6Fs1/78+QdU2MSr7mgsaCtzk=,tag:t9Ey+h4cOkXi113jqO2k2w==,type:str]
    litellm-key: ENC[AES256_GCM,data:aQAuVSM1kBwKGe5hHWIZORiy8foYmO8kzg07Ca9VX3CZ0JMlmA8vMMMy30Wmqw+uajsFNel7n8nmEzBVWNLPoQ==,iv:TlDw7HH7l042j2Us1V5DGfjQoGFMS65saLvTkyBtK/c=,tag:sUdFJAjhqcpfn2cood+rQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rj2w4scur86mjvs6eutq03cwlpygu3pywcedvl0rkh68vzv0dlqagqenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeDh3K04rV2RuZ09SUFY0
            TEVNWTJ5cXgwSDNJblVBUHBSWk44MlF0SVZnCmcyTHJuTHV4ODF4MWxYYUI2VndS
            d2owSXdwQk5uZXRpMzdXdWxQUDlmV0EKLS0tIDlWWUU2M3NoQWZJWHYyamxrQ1lz
            b29KdXJtaWtYTHc5MjRVVlQ0ZC8yWjgKHBDQ0JHKx1wqTwBFtU6/R5+cWx0M6RGc
            S556wuzR8SGuytfKZzkFnP+P9v7aAyFX1YSb/u6+z8SAZn1m81Z9jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T17:38:29Z"
    mac: ENC[AES256_GCM,data:tzwPVNsl8QPu//buaJHLfWTsv+sePAxOdrAsLEOtLHToKSZwGbb17irK5MxP2BEGCWzy30F1ojfgsNFyskAlfPOL12ijzdG60q3YMVt8uTiesXIFYPFuMqgLSHNQQwmQEZTvZN79HZkzsX0qCAonW1IUBc80qspomxEyFLxmF+k=,iv:TIqdsDrCQbD37fYHCUGClvE9AXmcB36a7KQwMAd9uzE=,tag:DepSBCp9vP3Yvc7G0drH7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
