---
apiVersion: v1
kind: Secret
metadata:
  name: openai-proxy-tls
  namespace: openclaw
type: kubernetes.io/tls
stringData:
  tls.crt: |
    
-----BEGIN CERTIFICATE-----
MIIDLjCCAhagAwIBAgIUHvh/hvFQHF9QD8w3ghoh072SLPswDQYJKoZIhvcNAQEL
BQAwGTEXMBUGA1UEAwwOYXBpLm9wZW5haS5jb20wHhcNMjYwMzE1MTcwMjE4WhcN
MzYwMzEyMTcwMjE4WjAZMRcwFQYDVQQDDA5hcGkub3BlbmFpLmNvbTCCASIwDQYJ
KoZIhvcNAQEBBQADggEPADCCAQoCggEBANEP6HDcy2I1b26xQVUBA13IxA6G08n9
fHo87vRHKpwOkdgAOGMFJ+MYj1X8LHZfIeUAGR3IjJVmiepAUzAfhHICZTvetRNO
9ISz4YU6eacawHz1rlSfGRfPdGSxNeqgRzJMH1xryErKKfNR1BHAh9eljqUEKeCK
vZ6n2W/U6d74NXBBJhX0AsyIC8zA0dLVGagJYH7I/6uvXOQUCTXWKk8f2+1HScbq
K/3V5Wp35BmH9xbrxVfYbWqLBaaPpzHaGlc4xViYcfPCQ5sLlJdd9MbZISR8ajqo
PdUOlwEfoeDRDJVnOBGnIsLUv298JSEmpokzI/YaaB533hw2mv/AOx0CAwEAAaNu
MGwwHQYDVR0OBBYEFOEvj1p5fh0xAVJVqYOVZb/vtzSGMB8GA1UdIwQYMBaAFOEv
j1p5fh0xAVJVqYOVZb/vtzSGMA8GA1UdEwEB/wQFMAMBAf8wGQYDVR0RBBIwEIIO
YXBpLm9wZW5haS5jb20wDQYJKoZIhvcNAQELBQADggEBAKxkf2kEBgrxahY1Ugy8
Ng3z3SdU5uNHS3ltHHurp9H6eVORr5KrUqyE6tC/UlUA+YlDcP4oYYSP/VAX4ws4
Fpahketpr1DFFS6q0qbYFxgHHevj1WZovuGK4zLfeSYN2Y/GSO85LE4w+QDtd0W8
rvvrcBwQIAnMfk43V0tepcqUH+PhEQjiZ2NVzOaQ6aS0pf8vU9I+lJ5oINIg0K5t
+qjfyKkpfXAwMrav8WpDEkZHXE6rR/zP1RSGggdUKToRT9xt6xw/ZCU6/1uA4Df7
BLfdGYLqRbqFxEBw0j6tRDafpmcXGMlSc97e72F4NCPreSIj3q/xGp5phxFR7Bai
91A=
-----END CERTIFICATE-----
  tls.key: |
    
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDRD+hw3MtiNW9u
sUFVAQNdyMQOhtPJ/Xx6PO70RyqcDpHYADhjBSfjGI9V/Cx2XyHlABkdyIyVZonq
QFMwH4RyAmU73rUTTvSEs+GFOnmnGsB89a5UnxkXz3RksTXqoEcyTB9ca8hKyinz
UdQRwIfXpY6lBCngir2ep9lv1One+DVwQSYV9ALMiAvMwNHS1RmoCWB+yP+rr1zk
FAk11ipPH9vtR0nG6iv91eVqd+QZh/cW68VX2G1qiwWmj6cx2hpXOMVYmHHzwkOb
C5SXXfTG2SEkfGo6qD3VDpcBH6Hg0QyVZzgRpyLC1L9vfCUhJqaJMyP2Gmged94c
Npr/wDsdAgMBAAECggEAZe0rllsPjcIfoggpohfsXD0V2T9C4qgDmFU86zwHOi6g
TH9O/nf1CnNe7r0TsGKRU+TIWgz8/ZoQg3T5Ge1D1ZH1aUsbXV6ROGG7AgmQZjhU
wJfHdtpakZFDXhRIBSw/ifYzFAw4ir4l1ct/aWhE0o6VDT8Ka78407FiAXP80geu
yt1ZaGuRzjQsIBXoKZ7pSVAIP1LOQo548lu0ioSOaQ4rUJ6qrh4Yhz5ggaoLHIA6
5soi26AOc9rqmk8w17SnNoB9sgT13veGcdPjIu+auh42P1J1impcasTQdXOX7kJU
+IA6Z4NDxYT6sMqI3Mg+BmrjzpvODaBznDhDWA2EwQKBgQD/5fVeGZvt/pOYGQHZ
fu5YKyW3PGPx9rkliOnTJk7YSfUIQS0WFnhNI0jt1Zd6ytJfv653Zu1zzz2eycPK
wFS/p7TUIzsZxnWce5AggiDOj3K/DcSgrjFwVg05Yk/2dJKZ44f5w4DB15ZLUvgm
CSLQ55d2eE1T5bYZatobKRxaswKBgQDRJS7nWLsXi+NR00PW35MF4GuIUbBzMTTP
YrDi0GKV+zIZSlcAscjcHm/u/gm3EVex8tMVfYV+gr4YXe+Jk3KllrZqliDnFHNz
pJdcDmw27oPdTSFAJs7xu8I0hD4xPaC+4ecKMnqjgi8ybkKrU1vxt1RSJHREuyP0
Jo/ocNk67wKBgQCRd6DHEFnCrfArCzQw9mX5OvXitvK9zporSyxYurMhYtFnEt3V
a4qRlxhTExNcW0XB5k4AVENxjQKjbGDftfu3Q1eZLDnhih67iMZCpJaPtZ3uG56G
FN/H0zMLRubb3CKmVmCqy8c66hnm0dB8lr7y8GP6laKnqbKduk8oF3Ol3wKBgEEf
ue4x0/guB/e3uD0VWxuOWQ2WmkIURWR6T6ggyUH4eQ4k9thxg6D/HU2m7vGBRfRU
L2RWtJXDMlw2C9uj/SQQvPaNjutFk/mje7ofh5THSmpDlSH7s57UH1HpB9CfZwlp
IF8tfsChTf7/FGVyzIOE2Y3Gainot/ZTd6YiVZIjAoGAUQkEuID8YMuHzHE/qIwp
sPoGNBRmuyZDuotvmSPgvZlZ6A3/I9KO+N8s6KI+Ux1Fp/X5NRRBEMJf+U133iMr
kjaNkNw1KRcw2ip3I63j9AbU9SSW5kcgWaJteQTgml2+r/ZJLjb5y8orPvNc+ige
unQbQtnUfM6fQZyM7/aPpVM=
-----END PRIVATE KEY-----
