apiVersion: v1
kind: secret
metadata:
    name: unifi-user
    namespace: networking
stringData:
    UNIFI_USER: ENC[AES256_GCM,data:N9MgCjkxJwMjFkNK,iv:xlFXBR2NabraFG1fhOIrh/TbM7yAVLDiAKLonZspUKo=,tag:34+GEPeo72GXhDpMX8tW2A==,type:str]
    UNIFI_PASSWORD: ENC[AES256_GCM,data:Lc552uco6b8cEv84fil6MA==,iv:U4L/eGUIKI3sDFq1nWwlMD2X8SOv1dbEVIzdZ3pWyCI=,tag:z7Y6TcK9bfbZopQwMlv1Ng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rj2w4scur86mjvs6eutq03cwlpygu3pywcedvl0rkh68vzv0dlqagqenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyd3lZMEtrT0kzelA1bjN0
            TFhKb0xacGo2UlNOcUlPN0Rjd3VEcTVPN3hzCmFsbC9QNmZ2cXFOY2VxVlpsQ0pj
            L1BJd1BEWjdnaWM4UlF6Ui9MSmZYUmMKLS0tIFowbGlaN1hmOFNxR2xLSFVoRXpW
            VE0xKzFoZlNLYms2ckNnMmdFYWJLejQKK8ogNmFHzcPvfgnUqHpmsBViQic6e/sX
            V0rCdD0Ni7Od0X6aqwBN7oj+WggFxiYX+IggG8dKbN0ok73XTi1jJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T17:52:15Z"
    mac: ENC[AES256_GCM,data:NMKm+Qmiv/dxINLJgKTMNR7+IXIU6pktRDuk0NvI0UVx7UmNcuETJhB6NJY4/EddPEoYky72eehyu+jw5JLuIpDZdN/Tj0I1LbUgBlS7rUhrMd426YlS+DwIwdsuMgKWRtkVfdXAWSyZsMLxTtchL/RJuKWH3F+zrbZnS6/B6fw=,iv:eHe2tqFr2VNUpVCVvlXYVw1PxNUG2ju0P79E4ZMlE5Q=,tag:H36K+KoM9WxAAtKzgj4Hsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
