apiVersion: ENC[AES256_GCM,data:2LI=,iv:/iAGv2Fpxu1yqGPyWmZbP3wK6Sq1pirlKRrA0+iMGJ0=,tag:9jOacEylsk+H6poFi4JH7A==,type:str]
kind: ENC[AES256_GCM,data:YpBTJwig,iv:w7/VUykuG1kUT1DkTWjqlWCo0sMpkCAdtomgi2hO95U=,tag:OvtL9IJvsi2VO72EjyyS5w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FQc4CGnVNUQVKA==,iv:n8DEkA5moaOIrwEEHJihZN8LpOQ++o+fScticOkMk88=,tag:GQFuabSKywDPFRxu4WWKEw==,type:str]
    namespace: ENC[AES256_GCM,data:RcWT3h1yflxxpg==,iv:ud8ZhqXJXTVNxMKnzvjMGxnXoWUyn/q2e0ftt9W7uVg=,tag:r9zwJoS6bpJK/af74nldBg==,type:str]
stringData:
    UNIFI_USER: ENC[AES256_GCM,data:MqyxpUDteQlpFLJL,iv:+1N0vSw+VYQVcCv7ZDJ/SmMUuQr4WvZYeJ87y3B0/Aw=,tag:oMpj/89Rct+J/ApbISQBlg==,type:str]
    UNIFI_PASSWORD: ENC[AES256_GCM,data:nbasCYBURgkrw3yklbFwAA==,iv:ue6/u+pFKAAtT7gejSTuvgXhSuRcajglIRHwRYrk11c=,tag:LivYcCXBrLMGwI2E7E/Uyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rj2w4scur86mjvs6eutq03cwlpygu3pywcedvl0rkh68vzv0dlqagqenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQU9iVGREOXp1U0tQYWpP
            UWtORk4yREFZQy93RTdLQ2FkNDJYRXBQRkJ3Cm1qd1VDa2dJQytMZ3YvdXowOWRP
            OTMwSityTlRUcVN1MkN6Ry9rMk1BcUEKLS0tICtUR1pETzRWeGkxRU8xN1lKVzVZ
            OE1qSmpjMXE1QisrT3F5c1haK1Q3RTgK5iBasgQCcAV3ZWCG39cSi5aPN1FLc2Py
            Q3JZaX4TUWPzrU7PhtD1UGlh2C3BO4CVU/NMzLK0dTkbAN22ItlDxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T17:47:35Z"
    mac: ENC[AES256_GCM,data:jS7ci37Nsh070qe0OlVPP36A3zCdBjeE4CMJ+ezEi/skFsCHUncjE8dUOlmFLXyjQfbPAnqs1yekH65+S1Y/CUPPM9zpL2AnHEqKjtftzQRwbIdX/p69tRL+lSoP/2iEPGfvXk4xr3Tma11nAQA+ZcUQKR7BZyBXutPf3SYJsXk=,iv:xmczRnJuNqDEndwy7oV5TEFq+wFdhWYVmRx05mol4i8=,tag:as6FdYAu4yHbOTflh7BFiQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
