---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: games
spec:
  interval: 10m
  chart:
    spec:
      chart: minecraft-bedrock-server
      # renovate: datasource=helm registryUrl=https://home-ops.andrewmccall.com/charts/stable chart=minecraft-bedrock-server
      version: 0.11.3
      sourceRef:
        kind: HelmRepository
        name: home-ops
        namespace: flux-system
  values:
    service:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "minecraft.${DOMAIN}"
        type: LoadBalancer
        externalIPs:
          - ${MINECRAFT_IP}
        externalTrafficPolicy: Local
    persistence:
      config:
        enabled: true
        existingClaim: minecraft-bedrock-pvc

    minecraftServer:
      eula: "TRUE"
      serverName: "Dig!!"
