---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: minecraft-bedrock
      # renovate: datasource=helm registryUrl=https://itzg.github.io/minecraft-server-charts/ chart=minecraft-bedrock
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
  values:
    minecraftServer:
      eula: "TRUE"
      serverName: "McMinecraft"
    service:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "minecraft.${DOMAIN}"
        type: LoadBalancer
        externalIPs:
          - ${MINECRAFT_IP}
        externalTrafficPolicy: Local
