---
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecreft
  namespace: games
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      minecraft:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: itzg/minecraft-bedrock-server
              tag: 2025.9.0@sha256:5db52aa35919573eaa4f2d8e0f934aab3e306ab66080d642d4d22da988fe2463
            env:
              TZ: Europe/London
              EULA: "TRUE"
              SERVER_NAME: "home server"
              OPS: ${MINECRAFT_OPS}
              DIFFICULTY: normal
    service:
      app:
        controller: minecraft
        ports: 
          server:
            port: 19132
            protocol: UDP
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "minecraft.${DOMAIN}"
        type: LoadBalancer
        externalIPs:
          - ${MINECRAFT_IP}
        externalTrafficPolicy: Local
    persistence:
      config:
        existingClaim: minecraft-bedrock-pvc
        globalMounts:
          - path: /data