---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: coredns
      # renovate: datasource=helm registryUrl=https://coredns.github.io/helm chart=coredns
      version: 1.19.7
      sourceRef:
        kind: HelmRepository
        name: coredns
        namespace: flux-system
  values:
    replicaCount: 1
    isClusterService: true
    serviceAccount:
      create: true
    serviceType: LoadBalancer
    service:
      externalIPs:
        - ${COREDNS_IP}
      externalTrafficPolicy: Local
    zoneFiles:
      - filename: home.db
        domain: ${DOMAIN}
        contents: |
          $TTL 300 ;
          ${DOMAIN}.          IN SOA    ns.${DOMAIN}. hostmaster.${DOMAIN}. 2021072001 7200 1800 86400 30
          ns.${DOMAIN}.       IN A      ${COREDNS_IP}
          vecna.${DOMAIN}.    IN A      10.0.0.250
          unifi.${DOMAIN}.    IN A      ${UNIFI_IP}
          home.${DOMAIN}.     IN A      ${INGRESS_NGINX_IP}
    servers:
      # only 1 protocol per port so scheme is required here to limit to udp
      # feature gate MixedProtocolLBService allows multi-protocol per port
      # for LoadBalancer
      - zones:
          - zone: ${CLUSTER_DOMAIN}.
            scheme: dns://
          - zone: ${DOMAIN}.
            scheme: dns://
          - zone: .
            scheme: dns://
            use_tcp: false
        port: 53
        plugins:
          - name: debug
          - name: health
            configBlock: |-
              lameduck 5s
          - name: ready
          - name: kubernetes
            parameters: ${CLUSTER_DOMAIN} in-addr.arpa ip6.arpa
            configBlock: |-
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
              ttl 30
          - name: etcd
            parameters: ${DOMAIN}
            configBlock: |-
              fallthrough
              path /skydns
              endpoint http://etcd-extdns:2379
          - name: file
            parameters: /etc/coredns/home.db ${DOMAIN}
          #- name: prometheus
          #  parameters: 0.0.0.0:9153
          - name: forward
            parameters: . 10.0.0.1:53
          - name: cache
          - name: loop
          - name: reload
    prometheus:
      service:
        enabled: true
      monitor:
        enabled: true
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - coredns
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - coredns
            topologyKey: kubernetes.io/hostname
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 200Mi
