---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: coredns
      # renovate: datasource=helm registryUrl=https://coredns.github.io/helm chart=coredns
      version: 1.32.0
      sourceRef:
        kind: HelmRepository
        name: coredns
        namespace: flux-system
  values:
    replicaCount: 1
    isClusterService: false
    serviceAccount:
      create: true
    serviceType: LoadBalancer
    service:
      externalIPs:
        - ${COREDNS_IP}
      externalTrafficPolicy: Local
    servers:
      # only 1 protocol per port so scheme is required here to limit to udp
      # feature gate MixedProtocolLBService allows multi-protocol per port
      # for LoadBalancer
      - zones:
          - zone: ${CLUSTER_DOMAIN}.${DOMAIN}
            scheme: dns://
          - zone: ${DOMAIN}.
            scheme: dns://
          - zone: .
            scheme: dns://
            use_tcp: false
        port: 53
        plugins:
          - name: log
          - name: errors
          - name: health
            configBlock: |-
              lameduck 5s
          - name: ready
          - name: file
            parameters: /etc/coredns/ingress.db ingress.${DOMAIN}
          - name: etcd
            configBlock: |-
              fallthrough
              path /skydns
              endpoint http://${ETCD_EXTDNS_IP}:2379
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: forward
            parameters: . 1.1.1.2:53
          - name: cache
          - name: loop
          - name: reload
    prometheus:
      service:
        enabled: true
      monitor:
        enabled: true
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - coredns
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - coredns
            topologyKey: kubernetes.io/hostname
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 200Mi
