---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi-poller
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: unifi-poller
      version: 11.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: golift/unifi-poller
      tag: v2.21.0@sha256:a08b532be181256318211b6170691e316d29ac04575bc54d59620189953f03aa
    env:
      UP_UNIFI_DEFAULT_URL: ${UNIFI_CONTROLLER_URL}
      UP_INFLUXDB_DISABLE: true
    envFrom:
      - secretRef:
          name: unifi-poller-credentials
    metrics:
      enabled: true
      prometheusRule:
        enabled: true
    resources:
      requests:
        cpu: 300m
        memory: 200Mi
      limits:
        cpu: 300m
        memory: 200Mi
