---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi-poller
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: unifi-poller
      version: 11.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: golift/unifi-poller
      tag: v5.2.8@sha256:ca82e584b9bb3c8d2f9998adb429ab9f9bbb8840388ba10f2c62f07bd31ea0e9
    env:
      UP_UNIFI_DEFAULT_URL: ${UNIFI_CONTROLLER_URL}
      UP_INFLUXDB_DISABLE: true
    envFrom:
      - secretRef:
          name: unifi-poller-credentials
    metrics:
      enabled: true
      prometheusRule:
        enabled: true
    resources:
      requests:
        cpu: 300m
        memory: 200Mi
      limits:
        cpu: 300m
        memory: 200Mi
