---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi-poller
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: unifi-poller
      version: 11.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: golift/unifi-poller
      tag: v2.13.1@sha256:2376aff5e18b8f9fdd618becc2ef668ce31deb4c0e74acc5bea88e6c20c23a39
    env:
      UP_UNIFI_DEFAULT_URL: ${UNIFI_CONTROLLER_URL}
      UP_INFLUXDB_DISABLE: true
    envFrom:
      - secretRef:
          name: unifi-poller-credentials
    metrics:
      enabled: true
      prometheusRule:
        enabled: true
    resources:
      requests:
        cpu: 300m
        memory: 200Mi
      limits:
        cpu: 300m
        memory: 200Mi
