---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  interval: 10m
  chart:
    spec:
      chart: longhorn
      # renovate: datasource=helm registryUrl=https://charts.longhorn.io chart=longhorn
      version: 1.10.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      defaultClassReplicaCount: 1
