apiVersion: v1
kind: Secret
metadata:
    name: openclaw-api-keys
    namespace: openclaw
type: Opaque
stringData:
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:R3a57IK5+bLZn1AnjPyCGfDoYaNvlrdr3H5ajFtnTCL81JLnwLJx669BuzDornmk1f8zVs1ojtDf6HkkDp5HxfvnjQpZFgaCYQ==,iv:OZIUDwH7lVl0aC4WFllcB6/Rv2yQt7G9anUXvXIj4p4=,tag:UiHRqDYEJqj7osP8+S7J9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rj2w4scur86mjvs6eutq03cwlpygu3pywcedvl0rkh68vzv0dlqagqenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbU91L0dVQXpBVHRGTlRG
            dUpldCtuREtyMkFHeFBtZHBmbEFTclFYelNRCjRhTVNudXRhNUFkeTdDM0ZXTGtv
            YWNRM2lvNXlIZndHUjNtL3JodUxuUUUKLS0tIGhhdWdLUWZBeFNVSGxZeGRxbFd2
            SU5rWldzQ2Y4eXVqY0FKbFN6MlZnOUUKtS1S66F3k4TFSQPOp2bDCMgwJDL8jb+i
            NeRfui/HTPm3Y7SIF3YKXCayYz3vQFqLB8/H+19ZDCPHi9kPGvIWdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T17:27:32Z"
    mac: ENC[AES256_GCM,data:3sG9U5i9AaS8s4UvmwTmWAdFIsRHYzZmOh1CvNPgkETqiKD7tqDrHHUQ9CiBwuUFghxavSSJHjyT8aoaXE7awu1PchKG/N3qmjP35bXOyBxa0lrq+CdxR5wGgz/zgR+1moxfXn4BfpVrqfYKenmBZY4k7RXQgf1VYHiWbWP7BNQ=,iv:H8RIsClqLdYk8lgR9vEM5gU0TdHmKNzvnjKlSRNIueg=,tag:PRsDzTsQ4ZBa+eu+82PlPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
