apiVersion: v1
kind: Secret
metadata:
    name: openclaw-ha-voice-token
    namespace: openclaw
type: Opaque
stringData:
    HA_VOICE_GATEWAY_TOKEN: ENC[AES256_GCM,data:neMHUuXT+OIWgkmqa9n5iYIXr24y8WI9Vb54MD9qrxW1Rk1taMY7YWnfrPSxGQ==,iv:YWWrsEdzUj1tV3JqDmcbDYZSwjNfGsKnLncqkv8qRLs=,tag:ckaiNeMFRtWlFFt3pTWZ9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rj2w4scur86mjvs6eutq03cwlpygu3pywcedvl0rkh68vzv0dlqagqenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1L084dis4VGFSRGduZUc5
            R25udnc2elJrK3RibDdnckpxTk1CSXVHNjAwCkZtMHZrY3IxbW9HYkZkTUZqU2hH
            OHF2QmRaYmVSZzlVUzhCaVFoZFlBWDgKLS0tIEhEbUpuMFhHT2E4U2tuZW91NTha
            NnlsaGFxR29sZDZnSWxDQXowb1h6MXMKwFPynUqztrDXrvX5FglOMobIFTzaSl8U
            Ex89fLuILy5rQEJ8g0SQMyTwpUaXwv6RDWLo1z43STonYhot29YK8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T21:29:56Z"
    mac: ENC[AES256_GCM,data:m6f1/Uz7R/5haMAPTjRyPwjM47aQrKke05LQDICg6zenQx6pdrpORnJCBOrkP6zV896j+ozSor9JAhH0uE4xlUJaYHuJ+fcMAy4NbujO8SvGD+hgvpDl9NcYr9QhdWXeB0bcvdt8yzbtpthtzvzRRA2M4BC7qraG8Ukr+Nyio0g=,iv:KCQsvcrBfhm7eUngeRWuBU9ER68yzWOZ0999Tqvt3C8=,tag:YNDXpMCzIeoqF6rEwZxvSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
