---
# ./all.yaml
# This file setups everything calling the sub playbooks to build it all.

- import_playbook: bootstrap.yaml
- import_playbook: os.yaml

# Setup the k3s cluster now that we've done the specific setup
- import_playbook: cluster/cluster.yaml

# Setup 3dprinter stuff
- import_playbook: 3dprinter/printer_3d.yaml
