---
- hosts:
    - vecna
  become: yes
  vars_prompt:
    - name: "restart_confirmation"
      prompt: "Restart when complete? [Y/n]"
      default: "n"
      private: no
  tasks:
    - name: flush handlers
      meta: flush_handlers
