---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress
  namespace: networking
spec:
  secretName: ingress-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: ${DOMAIN}
  dnsNames:
    - "*.${DOMAIN}"
    - "${DOMAIN}"
