apiVersion: v1
kind: Secret
metadata:
    name: openclaw-bridge-secrets
    namespace: openclaw
stringData:
    bridge-api-key: ENC[AES256_GCM,data:JLRtTYCIR13nnDJMn0lHbZTUUN4m49kLoQzAJXiEQVPxBNZEEVnLk1C31X1xKuLn,iv:Q/DZfDV36iW7/5wCe/iMUZOHopo3vLMVYk9uqh4DjI8=,tag:sKX9wNtLHJIzWBH18PRVGA==,type:str]
    openclaw-gateway-token: ENC[AES256_GCM,data:Sk06y9SrjzBCvB3O7hkopuosq4/8ZoB/A2T2YmErCXtieHaVAXGKMMjRAEm1GzU9D8oZak9K4n4bTasbF+mIVw==,iv:fNBnoafu8GLekgn4uRnnRifbXblAH+KoeqOCWzRl9h0=,tag:duLeRkaHJgGX5E1LHwnR5w==,type:str]
    shared-session-key: ENC[AES256_GCM,data:73HAnu/RjL7LMH5XHe6KLnNRXOM=,iv:txJLLuJ4LT0LjdHhQSgYwuncVh6EI1BUN4Ofh+7kCac=,tag:0bVdA/tKzA8rNPh654Rjkg==,type:str]
    force-degraded-mode: ENC[AES256_GCM,data:K20edKE=,iv:d8i3EkYALBwlCt8aUo1mx8aePeZDCdQzWr5ovzFmWHQ=,tag:qrs2ndkxSiFtr8Y9DQCM9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rj2w4scur86mjvs6eutq03cwlpygu3pywcedvl0rkh68vzv0dlqagqenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcVBKd3NXWGt6eU9Vc25h
            UXRDTXdxUHkwa1hUL1Y2QmlVb2ZlMDhDWG5VCmZUQmJoWHhsclRUQy93WXhORFdn
            NGttY1VqYlBwaFh2MzJwRDBoOWxtdjAKLS0tIFo0bVJDOTRTSDduZjZNNnF5WERN
            NmNWRmxqRnRXRU1wV0g3Q3pZN2o1TEUKyjRMyRblt+DU7DR/HoHyWMDB0PSNSra5
            5JfSv/wr9PCDWHEdz0W1zGG8SolPfQ7QxnTYnk7RsGb8I7IfLIZDNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T08:09:09Z"
    mac: ENC[AES256_GCM,data:ciZbxdMw2cly0fgBI/Az4yQwhqbWnlI6p2BSF8liQSLztvHQX6ZFd/Qe46+kItvqPsEegzDu878hohb4JY9HwoY4GXuwjSIFa78UlksliHtb8EUVNaps8ITfJzhiBr9aqFelsVkrATGiAMifW6CyDrX4x+HF2eBwBh9xb7NixJw=,iv:LwBNsTfI2oUjy+xvFGhjLd5Qpdp+cFDkL54FKaSKg3Q=,tag:1skkm+4qjtnH0i4Qk8yjHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
