apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openclaw
resources:
  - bridge-runtime-configmap.yaml
  - bridge.yaml
  - bridge-secret.sops.yaml
  - openai-proxy-tls-secret.yaml
  - openai-proxy-ingress.yaml
