---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: databases
spec:
  interval: 10m
  chart:
    spec:
      chart: mosquitto
      # renovate: datasource=helm registryUrl=https://home-ops.andrewmccall.com/charts/stable chart=mosquitto
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: home-ops
        namespace: flux-system
  values:
    persistence:
      data:
        enabled: true
      configinc:
        enabled: true
