apiVersion: v2
name: common
description: Function library for home-ops charts.
type: library
version: 0.0.15
kubeVersion: ">=1.16.0-0"
keywords:
  - home-ops
  - k8s-at-home
  - common
home: https://github.com/andrewmccall/home-ops/tree/main/charts/library/common
maintainers:
  - name: Andrew McCall
    email: andrew@andrewmccall.com
