#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/andrewmccall/home-ops/tree/main/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: jlongster/actual-server
  # @default -- chart.appVersion
  tag: 23.3.1
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      # -- Configure Web interface + API port
      # @default -- See values.yaml
      http:
        port: 5006
        protocol: HTTPS

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: /data

