---
apiVersion: v2
appVersion: 1.19.1
description: Bridges events and allows you to control your Zigbee devices via MQTT
name: zigbee2mqtt
version: 9.4.3
kubeVersion: ">=1.16.0-0"
keywords:
  - zigbee
  - mqtt
  - home-assistant
icon: https://www.zigbee2mqtt.io/images/logo.png
sources:
  - https://github.com/Koenkk/zigbee2mqtt
dependencies:
  - name: common
    repository: https://home-ops.andrewmccall.com/charts/library/
    version: 1.0.3