---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vector-aggregator
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: vector
      # renovate: datasource=helm registryUrl=https://helm.vector.dev chart=vector
      version: 0.45.0
      sourceRef:
        kind: HelmRepository
        name: vector
        namespace: flux-system
  dependsOn:
    - name: loki
      namespace: monitoring
  values:
    image:
      repository: timberio/vector
      tag: 0.49.0-debian@sha256:6a56f8ee78e014d53a32fd7c6f6be9c18244fe861d938932fad8d6e65d3f5926
    role: Stateless-Aggregator
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: false
      sources:
        journal_logs:
          type: vector
          address: 0.0.0.0:6000
          version: "2"
        kubernetes_logs:
          type: vector
          address: 0.0.0.0:6010
          version: "2"
        vector_metrics:
          type: internal_metrics
      sinks:
        loki_journal:
          type: loki
          inputs:
            - journal_logs
          endpoint: http://loki-gateway:80
          encoding:
            codec: json
          batch:
            max_bytes: 2049000
          out_of_order_action: accept
          remove_label_fields: true
          remove_timestamp: true
          labels:
            hostname: >-
              {{`{{ host }}`}}
        loki_kubernetes:
          type: loki
          inputs:
            - kubernetes_logs
          endpoint: http://loki-gateway:80
          encoding:
            codec: json
          batch:
            max_bytes: 2049000
          out_of_order_action: accept
          remove_label_fields: true
          remove_timestamp: true
          labels:
            node: >-
              {{`{{ kubernetes.pod_node_name }}`}}
            namespace: >-
              {{`{{ kubernetes.pod_namespace }}`}}
            pod: >-
              {{`{{ kubernetes.pod_name }}`}}
            container: >-
              {{`{{ kubernetes.container_name }}`}}
            app: >-
              {{`{{ kubernetes.pod_labels."app.kubernetes.io/name" }}`}}
            instance: >-
              {{`{{ kubernetes.pod_labels."app.kubernetes.io/instance" }}`}}
        prometheus_sink:
          type: prometheus_exporter
          inputs:
            - vector_metrics
          address: 0.0.0.0:9090
    service:
      enabled: true
      type: LoadBalancer
    podMonitor:
      enabled: true
      jobLabel: vector-aggregator
      port: prometheus-sink
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: Service
              name: vector-aggregator
            patch:
              - op: add
                path: /spec/externalIPs
                value:
                  - "${VECTOR_IP}"
              - op: replace
                path: /spec/externalTrafficPolicy
                value: Local
