apiVersion: v1
entries:
  minecraft-bedrock:
  - apiVersion: v2
    appVersion: v1.19.51
    created: "2023-01-01T20:15:43.49734739Z"
    dependencies:
    - name: common
      repository: https://home-ops.andrewmccall.com/charts/library/
      version: 1.0.1
    description: Minecraft Bedrock Server
    digest: ae2939446de29c7db6740c9994978ca4a9292cf758292376d240c16019f2f20d
    home: https://github.com/andrewmccall/home-ops/tree/master/charts/stable/minecraft-bedrock
    keywords:
    - minecraft
    - game
    maintainers:
    - email: andrew@andrewmccall.com
      name: Andrew McCall
    name: minecraft-bedrock
    sources:
    - https://github.com/itzg/
    urls:
    - https://github.com/andrewmccall/home-ops/releases/download/minecraft-bedrock-0.11.1/minecraft-bedrock-0.11.1.tgz
    version: 0.11.1
  - apiVersion: v2
    appVersion: v1.19.51
    created: "2023-01-01T19:27:46.607704496Z"
    dependencies:
    - name: common
      repository: https://home-ops.andrewmccall.com/charts/library/
      version: 1.0.1
    description: Minecraft Bedrock Server
    digest: 8186405120876fa43374c1846cc25f89073985f930fa79382f6125dc68f373c3
    home: https://github.com/andrewmccall/home-ops/tree/master/charts/stable/minecraft-bedrock
    keywords:
    - minecraft
    - game
    maintainers:
    - email: andrew@andrewmccall.com
      name: Andrew McCall
    name: minecraft-bedrock
    sources:
    - https://github.com/itzg/
    urls:
    - https://github.com/andrewmccall/home-ops/releases/download/minecraft-bedrock-0.11.0/minecraft-bedrock-0.11.0.tgz
    version: 0.11.0
  - apiVersion: v2
    appVersion: v1.19.51
    created: "2023-01-01T17:30:22.930198305Z"
    dependencies:
    - name: common
      repository: https://home-ops.andrewmccall.com/charts/library/
      version: 1.0.1
    description: Minecraft Bedrock Server
    digest: 53b48d1677ee7086dbd507fca0401f66bffe986a58e412b6c3ab96a330be683a
    home: https://github.com/andrewmccall/home-ops/tree/master/charts/stable/minecraft-bedrock
    keywords:
    - minecraft
    - game
    maintainers:
    - email: andrew@andrewmccall.com
      name: Andrew McCall
    name: minecraft-bedrock
    sources:
    - https://github.com/itzg/
    urls:
    - https://github.com/andrewmccall/home-ops/releases/download/minecraft-bedrock-0.10.0/minecraft-bedrock-0.10.0.tgz
    version: 0.10.0
  - apiVersion: v2
    appVersion: v1.19.51
    created: "2023-01-01T17:02:41.636344176Z"
    dependencies:
    - name: common
      repository: https://home-ops.andrewmccall.com/charts/library/
      version: 1.0.1
    description: Minecraft Bedrock Server
    digest: 8cec41108925bfe5f4ba17e9342b98f4b6a06775a6c618ff3f2b74d775432931
    home: https://github.com/andrewmccall/home-ops/tree/master/charts/stable/minecraft-bedrock
    keywords:
    - minecraft
    - game
    maintainers:
    - email: andrew@andrewmccall.com
      name: Andrew McCall
    name: minecraft-bedrock
    sources:
    - https://github.com/itzg/
    urls:
    - https://github.com/andrewmccall/home-ops/releases/download/minecraft-bedrock-0.9.1/minecraft-bedrock-0.9.1.tgz
    version: 0.9.1
  - apiVersion: v2
    appVersion: v1.19.51
    created: "2023-01-01T16:36:28.361381654Z"
    dependencies:
    - name: common
      repository: https://home-ops.andrewmccall.com/charts/library/
      version: 1.0.1
    description: Minecraft Bedrock Server
    digest: 41166e6a454eb8a1250fdb729a9e59823f01300e673591c2bd7478ffd0455bb4
    home: https://github.com/andrewmccall/home-ops/tree/master/charts/stable/minecraft-bedrock
    keywords:
    - minecraft
    - game
    maintainers:
    - email: andrew@andrewmccall.com
      name: Andrew McCall
    name: minecraft-bedrock
    sources:
    - https://github.com/itzg/
    urls:
    - https://github.com/andrewmccall/home-ops/releases/download/minecraft-bedrock-0.9.0/minecraft-bedrock-0.9.0.tgz
    version: 0.9.0
  - apiVersion: v2
    appVersion: v1.19.51
    created: "2023-01-01T15:48:38.193862591Z"
    dependencies:
    - name: common
      repository: https://home-ops.andrewmccall.com/charts/library/
      version: 1.0.1
    description: Minecraft Bedrock Server
    digest: da7b953cba5f15d4f61cd0c0f0a9e7d958905ccaaffe90134175575911a81653
    home: https://github.com/andrewmccall/home-ops/tree/master/charts/stable/minecraft-bedrock
    keywords:
    - minecraft
    - game
    maintainers:
    - email: andrew@andrewmccall.com
      name: Andrew McCall
    name: minecraft-bedrock
    sources:
    - https://github.com/itzg/
    urls:
    - https://github.com/andrewmccall/home-ops/releases/download/minecraft-bedrock-0.0.9/minecraft-bedrock-0.0.9.tgz
    version: 0.0.9
  unifi:
  - apiVersion: v2
    appVersion: v7.1.68
    created: "2022-12-20T20:37:41.883035936Z"
    dependencies:
    - name: common
      repository: https://home-ops.andrewmccall.com/charts/library/
      version: 1.0.1
    - condition: mongodb.enabled
      name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.6.1
    description: Ubiquiti Network's Unifi Controller
    digest: 2cce0714ff87a93e0ab4f644f1281d1fce530b4b057b3469fec82eac4c6937ce
    home: https://github.com/andrewmccall/home-ops/tree/master/charts/stable/unifi
    icon: https://prd-www-cdn.ubnt.com/static/favicon-152.png
    keywords:
    - ubiquiti
    - unifi
    maintainers:
    - email: andrew@andrewmccall.com
      name: Andrew McCall
    name: unifi
    sources:
    - https://github.com/jacobalberty/unifi-docker
    urls:
    - https://github.com/andrewmccall/home-ops/releases/download/unifi-1.0.1/unifi-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: v7.1.68
    created: "2022-12-19T21:53:30.909496311Z"
    dependencies:
    - name: common
      repository: https://home-ops.andrewmccall.com/charts/library/
      version: 1.0.0
    - condition: mongodb.enabled
      name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 12.1.22
    description: Ubiquiti Network's Unifi Controller
    digest: e7cdb7016e754ce2a5cff4e06cd58e67a9a241a5f745a8cd3b40f8ea50acc583
    home: https://github.com/andrewmccall/home-ops/tree/master/charts/stable/unifi
    icon: https://prd-www-cdn.ubnt.com/static/favicon-152.png
    keywords:
    - ubiquiti
    - unifi
    maintainers:
    - email: andrew@andrewmccall.com
      name: Andrew McCall
    name: unifi
    sources:
    - https://github.com/jacobalberty/unifi-docker
    urls:
    - https://github.com/andrewmccall/home-ops/releases/download/unifi-1.0.0/unifi-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v2
    appVersion: v7.1.68
    created: "2022-12-19T21:30:22.658780145Z"
    dependencies:
    - name: common
      repository: https://home-ops.andrewmccall.com/charts/library/
      version: 0.0.17
    - condition: mongodb.enabled
      name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 12.1.22
    description: Ubiquiti Network's Unifi Controller
    digest: 53567e2e9ca1551b588cc650c95893ce9851919d939958f0492aa814d53ec8aa
    home: https://github.com/andrewmccall/home-ops/tree/master/charts/stable/unifi
    icon: https://prd-www-cdn.ubnt.com/static/favicon-152.png
    keywords:
    - ubiquiti
    - unifi
    maintainers:
    - email: andrew@andrewmccall.com
      name: Andrew McCall
    name: unifi
    sources:
    - https://github.com/jacobalberty/unifi-docker
    urls:
    - https://github.com/andrewmccall/home-ops/releases/download/unifi-0.0.10/unifi-0.0.10.tgz
    version: 0.0.10
generated: "2023-01-01T20:15:43.497379592Z"
