{{- include "common.values.setup" . }}

{{/* Append the hardcoded settings */}}
{{- define "minecraft.harcodedValues" -}}
env:
  EULA: "true"
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "minecraft.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "common.all" . }}
