---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 10m
  chart:
    spec:
      chart: kyverno
      # renovate: datasource=helm registryUrl=https://kyverno.github.io/kyverno/ chart=kyverno
      version: 3.2.6
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  values:
    crds:
      install: false
    admissionController:
      replicas: 1
      serviceMonitor:
        enabled: true
