---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 10m
  chart:
    spec:
      chart: kyverno
      # renovate: datasource=helm registryUrl=https://kyverno.github.io/kyverno/ chart=kyverno
      version: 3.0.9
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  values:
    installCRDs: false
    replicaCount: 1
    serviceMonitor:
      enabled: true
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: kyverno
