---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: etcd-extdns
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: etcd
      # renovate: datasource=helm registryUrl=https://charts.bitnami.com/bitnami chart=etcd
      version: 8.5.11
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      rbac:
        create: false
    persistence:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    service:
      clusterIP: ${ETCD_EXTDNS_IP}
