---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: etcd-extdns
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: etcd
      # renovate: datasource=helm registryUrl=https://charts.bitnami.com/bitnami chart=etcd
      version: 12.0.18
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    logLevel: "debug"
    auth:
      rbac:
        create: false
    clusterDomain: ${CLUSTER_DOMAIN}
    persistence:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    service:
      clusterIP: ${ETCD_EXTDNS_IP}
