---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: house
spec:
  interval: 10m
  chart:
    spec:
      chart: zigbee2mqtt
      # renovate: datasource=helm registryUrl=https://home-ops.andrewmccall.com/charts/stable chart=zigbee2mqtt
      version: 9.4.6
      sourceRef:
        kind: HelmRepository
        name: home-ops
        namespace: flux-system
  values:
    replicas: 1
    persistence:
      data:
        enabled: true
        size: 5Gi
      usb:
        enabled: true
        hostPath: /dev/ttyUSB0   
    securityContext:
      privileged: true
    config:
      homeassistant: true

      permit_join: true
      serial:
        port: /dev/ttyUSB0
      mqtt:
        server: "mqtt://mosquitto.daatabases.svc.cluster.home.andrewmccall.com:1883"
        