---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-dns-crds
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/kubernetes-sigs/external-dns.git
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include crd directory
    !/docs/contributing/crd-source/crd-manifest.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns-crds
  namespace: flux-system
spec:
  interval: 30m
  prune: false
  sourceRef:
    kind: GitRepository
    name: external-dns-crds