---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-installation
  namespace: flux-system
spec:
  interval: 10m
  ref:
    # renovate: datasource=github-releases depName=fluxcd/flux2
    tag: "v0.41.2"
  url: https://github.com/fluxcd/flux2
  ignore: |
    # exclude all
    /*
    # path to manifests
    !/manifests
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-installation
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/install
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-installation
  images:
    - name: fluxcd/helm-controller
      newName: ghcr.io/fluxcd/helm-controller
    - name: fluxcd/image-automation-controller
      newName: ghcr.io/fluxcd/image-automation-controller
    - name: fluxcd/image-reflector-controller
      newName: ghcr.io/fluxcd/image-reflector-controller
    - name: fluxcd/kustomize-controller
      newName: ghcr.io/fluxcd/kustomize-controller
    - name: fluxcd/notification-controller
      newName: ghcr.io/fluxcd/notification-controller
    - name: fluxcd/source-controller
      newName: ghcr.io/fluxcd/source-controller
  patches:
    - target:
        group: networking.k8s.io
        version: v1
        kind: NetworkPolicy
      patch: |-
        $patch: delete
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: not-used
  patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      namespace: flux-system
      name: source-controller
    patch: 
      - op: replace
        path: /spec/template/spec/containers/0/args/0
        value: --events-addr=http://notification-controller.flux-system.svc.cluster.home.andrewmccall.com/
      - op: replace
        path: /spec/template/spec/containers/0/args/6
        value: --storage-adv-addr=source-controller.flux-system.svc.cluster.home.andrewmccall.com
  - target:
      group: apps
      version: v1
      kind: Deployment
      namespace: flux-system
      name: helm-controller
    patch: 
      - op: replace
        path: /spec/template/spec/containers/0/args/0
        value: --events-addr=http://notification-controller.flux-system.svc.cluster.home.andrewmccall.com
  - target:
      group: apps
      version: v1
      kind: Deployment
      namespace: flux-system
      name: image-automation-controller
    patch: 
      - op: replace
        path: /spec/template/spec/containers/0/args/0
        value: --events-addr=http://notification-controller.flux-system.svc.cluster.home.andrewmccall.com
  - target:
      group: apps
      version: v1
      kind: Deployment
      namespace: flux-system
      name: image-reflector-controller
    patch:
      - op: replace
        path: /spec/template/spec/containers/0/args/0
        value: --events-addr=http://notification-controller.flux-system.svc.cluster.home.andrewmccall.com
  - target:
      group: apps
      version: v1
      kind: Deployment
      namespace: flux-system
      name: kustomize-controller
    patch: 
      - op: replace
        path: /spec/template/spec/containers/0/args/0
        value: --events-addr=http://notification-controller.flux-system.svc.cluster.home.andrewmccall.com
