---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
spec:
  name: cert-manager
resources:
  - helmrelease.yaml

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
spec:
  name: certs
  dependsOn:
    - name: cert-manager
resources:
  - cloudflare-api-token-secret.enc.yaml
  - letsencrypt-staging-clusterissuer.yaml
  - letsencrypt-production-clusterissuer.yaml
