---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - cloudflare-api-token-secret.enc.yaml
  # The below need to be uncommented for the first run, not ideal.
  - letsencrypt-staging-clusterissuer.yaml
  - letsencrypt-production-clusterissuer.yaml


